AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - files
  Include:
    - lib/*.rb
    - bin/*
    - spec/*_spec.rb

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/MethodLength:
  Max: 20